### ISSUE TITLE
Browser warning about unsaved content in side-by-side view

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#2013]
### Describe the Bug
When editing and saving information in the side by side view, some browsers display an unsaved content warning. This should be suppressed.

### Steps to Reproduce

1. Open any translation side by side view in Chrome 109 
2. Edit and click publish
3. See browser warning about loosing unsaved content

### Expected Behavior
The browser warning should be suppressed for the save action.

### Actual Behavior
Browser does not recognize that the publish button is saving content.

### Additional Information
Related to: #1632
https://chat.tuerantuer.org/digitalfabrik/pl/7mgbz37i9pgy9jpfbugq5htayo

**Comment by JoeyStk** [comment]
The same bug occurs when leaving the German view to translation view

**Comment by timoludwig** [comment]
> The same bug occurs when leaving the German view to translation view

Indeed, there is a different ticket for this: #1632

**Comment by timoludwig** [comment]
This was apparently fixed in #2243.

**Comment by david-venhoff** [comment]
I can still (or again) reproduce this, by opening the sbs view, writing something in the text field and then clicking save. Then the unsaved warning still shows up

**Comment by osmers** [comment]
Closing as side by side view is rarely used, can reopen if reports about this behaviour come in from municipalities
